# Semantic Release configuration for mock-kv
# See https://semantic-release.gitbook.io/semantic-release/usage/configuration for details
branches:
  - main
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/npm'
    - npmPublish: false
  - '@semantic-release/github'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - package.json
        - pnpm-lock.yaml
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
