nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

npmScopes:
  variablesoftware:
    npmAlwaysAuth: false
    npmRegistryServer: "https://registry.npmjs.org"
    npmAuthToken: "${NPM_TOKEN}"
