name: Call Prune Releases

on:
  workflow_dispatch:
  release:
    types: [published, created]

jobs:
  prune_releases:
    uses: variablesoftware/github-workflows/.github/workflows/prune-releases.yaml@main
    secrets: inherit